// Regions of the Second World War, 1939–1945, assembled from Natural Earth admin-1 units
// along the frontiers of September 1939 where modern provinces allow (Poland, the Baltic
// states, Czechoslovakia, Austria inside the Reich, Japan's empire in Korea, Taiwan and
// Manchuria). Member syntax as in scripts/regions/napoleonic.mjs.

export const THEATRE = [-20, -15, 180, 72];
// Keep the Pacific atolls (Saipan, Kwajalein, Tarawa), which are smaller than the usual sliver cut-off.
export const SLIVER_KM2 = 1;

const names = (a, list) => list.split('|').map((n) => `${a}:${n}`);
const reg = (a, ...rs) => rs.map((r) => ({ a, r }));

export const REGIONS = [
  // ── Western Europe ──────────────────────────────────────────────────────
  { id: 'paris', name: 'Paris & the Loire', members: reg('FRA', 'Île-de-France', 'Centre-Val de Loire') },
  { id: 'north-france', name: 'Northern France', members: reg('FRA', 'Hauts-de-France') },
  { id: 'normandy', name: 'Normandy', members: reg('FRA', 'Normandie') },
  { id: 'brittany', name: 'Brittany & the Loire mouth', members: reg('FRA', 'Bretagne', 'Pays de la Loire') },
  { id: 'aquitaine', name: 'Aquitaine & Poitou', members: reg('FRA', 'Nouvelle-Aquitaine') },
  { id: 'champagne', name: 'Champagne & Lorraine', members: [{ a: 'FRA', r: 'Grand Est', not: ['Bas-Rhin', 'Haute-Rhin', 'Moselle'] }] },
  { id: 'alsace-moselle', name: 'Alsace & Moselle', members: ['FRA:Bas-Rhin', 'FRA:Haute-Rhin', 'FRA:Moselle'] },
  { id: 'burgundy', name: 'Burgundy & Franche-Comté', members: reg('FRA', 'Bourgogne-Franche-Comté') },
  { id: 'vichy-south', name: 'Lyon, Auvergne & Languedoc', members: reg('FRA', 'Auvergne-Rhône-Alpes', 'Occitanie') },
  { id: 'provence', name: 'Provence & Corsica', members: reg('FRA', "Provence-Alpes-Côte-d'Azur", 'Corse') },
  { id: 'belgium', name: 'Belgium', members: ['BEL'] },
  { id: 'luxembourg', name: 'Luxembourg', members: ['LUX'] },
  { id: 'netherlands', name: 'Netherlands', members: [{ a: 'NLD', not: ['Bonaire', 'St. Eustatius', 'Saba'] }] },
  { id: 'england', name: 'England & Wales', members: [{ a: 'GBR', g: 'England' }, { a: 'GBR', g: 'Wales' }, 'IMN'] },
  { id: 'scotland', name: 'Scotland & Ulster', members: [{ a: 'GBR', g: 'Scotland' }, { a: 'GBR', g: 'Northern Ireland' }] },
  { id: 'ireland', name: 'Ireland', members: ['IRL'] },
  { id: 'denmark', name: 'Denmark', members: ['DNK'] },
  { id: 'south-norway', name: 'Southern Norway', members: [{ a: 'NOR', not: ['Svalbard', 'Bouvet Island', 'Nordland', 'Troms', 'Finnmark'] }] },
  { id: 'north-norway', name: 'Northern Norway', members: names('NOR', 'Nordland|Troms|Finnmark') },
  { id: 'sweden', name: 'Sweden', members: ['SWE'] },
  { id: 'finland', name: 'Finland', members: ['FIN'] },
  { id: 'switzerland', name: 'Switzerland', members: ['CHE', 'LIE'] },
  { id: 'spain', name: 'Spain', members: [{ a: 'ESP', not: ['Ceuta', 'Melilla', 'Santa Cruz de Tenerife', 'Las Palmas'] }, 'AND'] },
  { id: 'portugal', name: 'Portugal', members: [{ a: 'PRT', not: ['Madeira', 'Azores'] }] },

  // ── The Reich and central Europe ────────────────────────────────────────
  { id: 'rhineland', name: 'Rhineland & Ruhr', members: names('DEU', 'Rheinland-Pfalz|Saarland|Nordrhein-Westfalen') },
  { id: 'north-germany', name: 'Hamburg & Lower Saxony', members: names('DEU', 'Niedersachsen|Bremen|Hamburg|Schleswig-Holstein') },
  { id: 'berlin', name: 'Berlin & Brandenburg', members: names('DEU', 'Brandenburg|Berlin|Sachsen-Anhalt|Mecklenburg-Vorpommern') },
  { id: 'saxony', name: 'Saxony & Thuringia', members: ['DEU:Sachsen', 'DEU:Thüringen'] },
  { id: 'southwest-germany', name: 'Baden-Württemberg & Hesse', members: ['DEU:Baden-Württemberg', 'DEU:Hessen'] },
  { id: 'bavaria', name: 'Bavaria', members: ['DEU:Bayern'] },
  { id: 'austria', name: 'Austria', members: ['AUT'] },
  { id: 'pomerania', name: 'Pomerania', members: ['POL:West Pomeranian', 'POL:Lubusz'] },
  { id: 'silesia', name: 'Silesia', members: ['POL:Lower Silesian', 'POL:Opole'] },
  { id: 'east-prussia', name: 'East Prussia', members: ['RUS:Kaliningrad', 'POL:Warmian-Masurian', 'LTU:Klaipedos'] },
  { id: 'bohemia', name: 'Bohemia & Moravia', members: ['CZE'] },
  { id: 'slovakia', name: 'Slovakia', members: ['SVK'] },
  { id: 'hungary', name: 'Hungary', members: ['HUN'] },
  { id: 'ruthenia', name: 'Carpathian Ruthenia', members: ['UKR:Transcarpathia'] },

  // ── Poland, the Baltic and the western Soviet Union ─────────────────────
  { id: 'west-poland', name: 'Western Poland', members: names('POL', 'Greater Poland|Pomeranian|Kuyavian-Pomeranian|Silesian') },
  { id: 'warsaw', name: 'Warsaw & Łódź', members: ['POL:Masovian', 'POL:Łódź', 'POL:Podlachian'] },
  { id: 'krakow', name: 'Kraków & Lublin', members: names('POL', 'Lesser Poland|Świętokrzyskie|Subcarpathian|Lublin') },
  { id: 'east-poland', name: 'Eastern Poland', members: [...names('UKR', "L'viv|Ternopil'|Ivano-Frankivs'k|Volyn|Rivne"), 'BLR:Grodno', 'BLR:Brest'] },
  { id: 'lithuania', name: 'Lithuania', members: [{ a: 'LTU', not: ['Klaipedos'] }] },
  { id: 'latvia', name: 'Latvia', members: ['LVA'] },
  { id: 'estonia', name: 'Estonia', members: ['EST'] },
  { id: 'belarus', name: 'Belorussia', members: names('BLR', 'Minsk|City of Minsk|Vitebsk|Mogilev|Gomel') },
  { id: 'kiev', name: 'Kiev & central Ukraine', members: names('UKR', "Zhytomyr|Kiev|Kiev City|Vinnytsya|Khmel'nyts'kyy|Cherkasy|Chernihiv|Sumy|Poltava") },
  { id: 'donbas', name: 'Kharkov & the Donbas', members: names('UKR', "Kharkiv|Donets'k|Luhans'k|Dnipropetrovs'k|Zaporizhzhya|Kirovohrad") },
  { id: 'odessa', name: 'Odessa & the Black Sea coast', members: names('UKR', 'Odessa|Mykolayiv|Kherson') },
  { id: 'crimea', name: 'Crimea', members: ['RUS:Crimea', 'RUS:Sevastopol'] },
  { id: 'bessarabia', name: 'Bessarabia & Bukovina', members: ['MDA', 'UKR:Chernivtsi'] },
  { id: 'leningrad', name: 'Leningrad', members: names('RUS', 'Leningrad|City of St. Petersburg|Novgorod|Pskov') },
  { id: 'karelia', name: 'Karelia & Murmansk', members: ['RUS:Karelia', 'RUS:Murmansk'] },
  { id: 'smolensk', name: 'Smolensk, Bryansk & Kursk', members: names('RUS', 'Smolensk|Bryansk|Orel|Kursk|Belgorod') },
  { id: 'moscow', name: 'Moscow', members: names('RUS', "Moskva|Moskovskaya|Kaluga|Tula|Tver'|Ryazan'|Vladimir|Yaroslavl'|Ivanovo|Lipetsk|Tambov") },
  { id: 'voronezh', name: 'Voronezh', members: ['RUS:Voronezh'] },
  { id: 'don', name: 'Rostov & the Kuban', members: names('RUS', "Rostov|Krasnodar|Adygey|Stavropol'") },
  { id: 'stalingrad', name: 'Stalingrad & the lower Volga', members: names('RUS', "Volgograd|Kalmyk|Astrakhan'|Saratov") },
  { id: 'caucasus', name: 'The Caucasus', members: [...names('RUS', 'Kabardin-Balkar|Karachay-Cherkess|North Ossetia|Chechnya|Ingush|Dagestan'), 'GEO', 'ARM', 'AZE'] },
  { id: 'north-russia', name: 'Archangel & the north', members: names('RUS', "Arkhangel'sk|Vologda|Kostroma|Kirov|Komi|Nenets") },
  { id: 'volga', name: 'The middle Volga & Urals', members: names('RUS', "Nizhegorod|Penza|Samara|Ul'yanovsk|Tatarstan|Chuvash|Mariy-El|Mordovia|Udmurt|Bashkortostan|Orenburg|Perm'|Sverdlovsk|Chelyabinsk") },
  { id: 'soviet-far-east', name: 'Soviet Far East', members: names('RUS', "Primor'ye|Khabarovsk|Amur|Yevrey|Chita|Buryat") },
  { id: 'sakhalin', name: 'Sakhalin & the Kurils', members: ['RUS:Sakhalin'] },
  { id: 'mongolia', name: 'Mongolia', members: ['MNG'] },

  // ── The Balkans and Italy ───────────────────────────────────────────────
  { id: 'slovenia', name: 'Slovenia', members: ['SVN'] },
  { id: 'croatia', name: 'Croatia', members: [{ a: 'HRV', not: ['Zadarska', 'Šibensko-Kninska', 'Splitsko-Dalmatinska', 'Dubrovacko-Neretvanska'] }] },
  { id: 'dalmatia', name: 'Dalmatia', members: names('HRV', 'Zadarska|Šibensko-Kninska|Splitsko-Dalmatinska|Dubrovacko-Neretvanska') },
  { id: 'bosnia', name: 'Bosnia-Herzegovina', members: ['BIH'] },
  { id: 'serbia', name: 'Serbia', members: ['SRB'] },
  { id: 'kosovo', name: 'Kosovo', members: ['KOS'] },
  { id: 'montenegro', name: 'Montenegro', members: ['MNE'] },
  { id: 'macedonia', name: 'Vardar Macedonia', members: ['MKD'] },
  { id: 'albania', name: 'Albania', members: ['ALB'] },
  { id: 'greek-thrace', name: 'Eastern Macedonia & Thrace', members: ['GRC:Anatoliki Makedonia kai Thraki'] },
  { id: 'north-greece', name: 'Salonika, Epirus & Thessaly', members: names('GRC', 'Kentriki Makedonia|Dytiki Makedonia|Ayion Oros|Ipeiros|Thessalia|Ionioi Nisoi') },
  { id: 'south-greece', name: 'Athens & the Peloponnese', members: names('GRC', 'Stereá Elláda|Attiki|Peloponnisos|Dytiki Ellada|Notio Aigaio|Voreio Aigaio') },
  { id: 'crete', name: 'Crete', members: ['GRC:Kriti'] },
  { id: 'bulgaria', name: 'Bulgaria', members: [{ a: 'BGR', not: ['Dobrich', 'Silistra'] }] },
  { id: 'south-dobruja', name: 'Southern Dobruja', members: ['BGR:Dobrich', 'BGR:Silistra'] },
  { id: 'north-transylvania', name: 'Northern Transylvania', members: names('ROU', 'Cluj|Bistrita-Nasaud|Salaj|Maramures|Satu Mare|Bihor|Mures|Harghita|Covasna') },
  { id: 'romania', name: 'Romania', members: [{ a: 'ROU', not: ['Cluj', 'Bistrita-Nasaud', 'Salaj', 'Maramures', 'Satu Mare', 'Bihor', 'Mures', 'Harghita', 'Covasna'] }] },
  { id: 'north-italy', name: 'Northern Italy', members: reg('ITA', 'Lombardia', 'Piemonte', "Valle d'Aosta", 'Liguria', 'Trentino-Alto Adige', 'Veneto', 'Friuli-Venezia Giulia', 'Emilia-Romagna') },
  { id: 'central-italy', name: 'Central Italy', members: reg('ITA', 'Toscana', 'Marche', 'Umbria', 'Lazio') },
  { id: 'south-italy', name: 'Southern Italy', members: reg('ITA', 'Campania', 'Abruzzo', 'Molise', 'Apulia', 'Basilicata', 'Calabria') },
  { id: 'sicily', name: 'Sicily', members: reg('ITA', 'Sicily') },
  { id: 'sardinia', name: 'Sardinia', members: reg('ITA', 'Sardegna') },
  { id: 'malta', name: 'Malta', members: ['MLT'] },

  // ── The Mediterranean, Africa and the Middle East ───────────────────────
  { id: 'turkey', name: 'Turkey', members: ['TUR'] },
  { id: 'cyprus', name: 'Cyprus', members: ['CYP'] },
  { id: 'syria', name: 'Syria & Lebanon', members: ['SYR', 'LBN'] },
  { id: 'palestine', name: 'Palestine & Transjordan', members: ['ISR', 'PSX', 'JOR'] },
  { id: 'iraq', name: 'Iraq', members: ['IRQ', 'KWT'] },
  { id: 'iran', name: 'Iran', members: ['IRN'] },
  { id: 'western-desert', name: 'The Western Desert', members: ['EGY:Matruh'] },
  { id: 'egypt', name: 'Egypt', members: [{ a: 'EGY', not: ['Matruh'] }] },
  { id: 'cyrenaica', name: 'Cyrenaica', members: names('LBY', 'Al Butnan|Al Qubbah|Al Jabal al Akhdar|Al Marj|Benghazi|Ajdabiya|Al Kufrah') },
  { id: 'tripolitania', name: 'Tripolitania & the Fezzan', members: [{ a: 'LBY', not: ['Al Butnan', 'Al Qubbah', 'Al Jabal al Akhdar', 'Al Marj', 'Benghazi', 'Ajdabiya', 'Al Kufrah'] }] },
  { id: 'tunisia', name: 'Tunisia', members: ['TUN'] },
  { id: 'algeria', name: 'Algeria', members: [{ a: 'DZA', clip: [-9, 32, 12, 38] }] },
  { id: 'morocco', name: 'Morocco', members: [{ a: 'MAR', not: ['Guelmim - Es-Semara', 'Laâyoune - Boujdour - Sakia El Hamra', 'Oued el Dahab'] }] },
  { id: 'eritrea', name: 'Eritrea', members: ['ERI'] },
  { id: 'ethiopia', name: 'Ethiopia', members: ['ETH'] },
  { id: 'italian-somaliland', name: 'Italian Somaliland', members: ['SOM'] },
  { id: 'british-somaliland', name: 'British Somaliland', members: ['SOL'] },

  // ── China, Japan and Korea ──────────────────────────────────────────────
  { id: 'japan', name: 'Japan', members: [{ a: 'JPN', not: ['Okinawa'] }] },
  { id: 'okinawa', name: 'Okinawa', members: ['JPN:Okinawa'] },
  { id: 'korea', name: 'Korea', members: ['KOR', 'PRK'] },
  { id: 'taiwan', name: 'Taiwan', members: [{ a: 'TWN', not: ['Kinmen'] }] },
  { id: 'manchuria', name: 'Manchuria', members: ['CHN:Heilongjiang', 'CHN:Jilin', 'CHN:Liaoning', { a: 'CHN', n: 'Inner Mongol', clip: [118, 30, 130, 60] }] },
  { id: 'mengjiang', name: 'Inner Mongolia', members: [{ a: 'CHN', n: 'Inner Mongol', clip: [97, 30, 118, 60] }] },
  { id: 'north-china', name: 'North China', members: names('CHN', 'Hebei|Beijing|Tianjin|Shanxi|Shandong') },
  { id: 'henan', name: 'Henan', members: ['CHN:Henan'] },
  { id: 'lower-yangtze', name: 'Shanghai, Nanjing & Zhejiang', members: names('CHN', 'Jiangsu|Shanghai|Anhui|Zhejiang') },
  { id: 'central-china', name: 'Wuhan, Hunan & Jiangxi', members: names('CHN', 'Hubei|Hunan|Jiangxi') },
  { id: 'canton', name: 'Canton & Hainan', members: ['CHN:Guangdong', 'CHN:Hainan', 'MAC'] },
  { id: 'hong-kong', name: 'Hong Kong', members: ['HKG'] },
  { id: 'fujian', name: 'Fujian', members: ['CHN:Fujian'] },
  { id: 'guangxi', name: 'Guangxi & Guizhou', members: ['CHN:Guangxi', 'CHN:Guizhou'] },
  { id: 'free-china', name: 'Sichuan & Yunnan', members: names('CHN', 'Sichuan|Chongqing|Yunnan') },
  { id: 'northwest-china', name: 'Shaanxi & Gansu', members: names('CHN', 'Shaanxi|Gansu|Ningxia|Qinghai') },

  // ── South-east Asia, India and the Pacific ──────────────────────────────
  { id: 'indochina', name: 'French Indochina', members: ['VNM', 'LAO', 'KHM'] },
  { id: 'thailand', name: 'Thailand', members: ['THA'] },
  { id: 'north-burma', name: 'Upper Burma', members: names('MMR', 'Kachin|Sagaing|Chin|Mandalay|Shan|Magway') },
  { id: 'south-burma', name: 'Rangoon & Lower Burma', members: names('MMR', 'Rakhine|Kayah|Kayin|Mon|Tanintharyi|Ayeyarwady|Yangon|Bago') },
  { id: 'malaya', name: 'Malaya & Singapore', members: [{ a: 'MYS', not: ['Sabah', 'Sarawak', 'Labuan'] }, 'SGP'] },
  { id: 'british-borneo', name: 'British Borneo', members: ['MYS:Sabah', 'MYS:Sarawak', 'MYS:Labuan', 'BRN'] },
  { id: 'sumatra', name: 'Sumatra', members: names('IDN', 'Aceh|Sumatera Utara|Sumatera Barat|Riau|Kepulauan Riau|Jambi|Sumatera Selatan|Bengkulu|Lampung|Bangka-Belitung') },
  { id: 'java', name: 'Java & Bali', members: names('IDN', 'Jakarta Raya|Banten|Jawa Barat|Jawa Tengah|Yogyakarta|Jawa Timur|Bali') },
  { id: 'dutch-borneo', name: 'Dutch Borneo', members: names('IDN', 'Kalimantan Barat|Kalimantan Tengah|Kalimantan Selatan|Kalimantan Timur') },
  { id: 'celebes', name: 'Celebes & the Moluccas', members: names('IDN', 'Sulawesi Utara|Gorontalo|Sulawesi Tengah|Sulawesi Barat|Sulawesi Selatan|Sulawesi Tenggara|Maluku|Maluku Utara') },
  { id: 'timor', name: 'Timor & the Lesser Sundas', members: ['IDN:Nusa Tenggara Barat', 'IDN:Nusa Tenggara Timur', 'TLS'] },
  { id: 'dutch-new-guinea', name: 'Dutch New Guinea', members: ['IDN:Papua', 'IDN:Papua Barat'] },
  { id: 'new-guinea', name: 'Papua & New Guinea', members: [{ a: 'PNG', not: ['North Solomons', 'East New Britain', 'West New Britain', 'New Ireland', 'Manus'] }] },
  { id: 'bismarcks', name: 'New Britain & Bougainville', members: names('PNG', 'North Solomons|East New Britain|West New Britain|New Ireland|Manus') },
  { id: 'solomons', name: 'Solomon Islands', members: ['SLB'] },
  { id: 'philippines', name: 'Philippines', members: ['PHL'] },
  { id: 'guam', name: 'Guam', members: ['GUM'] },
  { id: 'marianas', name: 'Saipan & the Marianas', members: ['MNP'] },
  { id: 'palau', name: 'Palau', members: ['PLW'] },
  { id: 'marshalls', name: 'Marshall Islands', members: ['MHL'] },
  { id: 'gilberts', name: 'Gilbert Islands', members: [{ a: 'KIR', clip: [170, -5, 180, 5] }] },
  { id: 'hawaii', name: 'Hawaii', members: ['USA:Hawaii'] },
  { id: 'northern-australia', name: 'Northern Australia', members: ['AUS:Northern Territory', 'AUS:Queensland'] },
  { id: 'east-india', name: 'Bengal & Assam', members: [...names('IND', 'West Bengal|Assam|Arunachal Pradesh|Nagaland|Manipur|Mizoram|Tripura|Meghalaya|Sikkim|Bihar|Jharkhand|Odisha'), 'BGD'] },
  { id: 'india', name: 'India', members: [{ a: 'IND', not: ['West Bengal', 'Assam', 'Arunachal Pradesh', 'Nagaland', 'Manipur', 'Mizoram', 'Tripura', 'Meghalaya', 'Sikkim', 'Bihar', 'Jharkhand', 'Odisha', 'Andaman and Nicobar'] }, 'PAK'] },
  { id: 'andamans', name: 'Andaman & Nicobar Islands', members: ['IND:Andaman and Nicobar'] },
  { id: 'ceylon', name: 'Ceylon', members: ['LKA'] },
];
